# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Golaunch < Formula
  desc "Launch your favorite apps with a single command"
  homepage "https://github.com/raufzer/golaunch-cli"
  version "1.0.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/raufzer/golaunch-cli/releases/download/v1.0.7/golaunch-cli_1.0.7_darwin_amd64.tar.gz"
      sha256 "ba8a06f171a6374f9a8c715cbd56cb03cdcd7785d3e8cb17c6df18efd65f4da9"

      def install
        bin.install "golaunch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/raufzer/golaunch-cli/releases/download/v1.0.7/golaunch-cli_1.0.7_darwin_arm64.tar.gz"
      sha256 "79c99a8fd832cd9c946a4a4c78766eb385e5446e1b42267acb0f09d904e6bfe7"

      def install
        bin.install "golaunch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/raufzer/golaunch-cli/releases/download/v1.0.7/golaunch-cli_1.0.7_linux_amd64.tar.gz"
        sha256 "cf3375aedd9befc90335533b618a90cc0319986df72364df77a1e5ada71392a8"

        def install
          bin.install "golaunch"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/raufzer/golaunch-cli/releases/download/v1.0.7/golaunch-cli_1.0.7_linux_arm64.tar.gz"
        sha256 "4478dc987ce1b4edbecf84b7689c0a6ae7db0a78b91977fb8b57509516508001"

        def install
          bin.install "golaunch"
        end
      end
    end
  end
end
