# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Golaunch < Formula
  desc "Launch your favorite apps with a single command"
  homepage "https://github.com/raufzer/golaunch-cli"
  version "1.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/raufzer/golaunch-cli/releases/download/v1.1.0/golaunch-cli_1.1.0_darwin_amd64.tar.gz"
      sha256 "15ed1f8b0d0e8d6af3e22d1495cb86204f8e1a12bfbfe3c77e78e4e29af9b9b6"

      def install
        bin.install "golaunch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/raufzer/golaunch-cli/releases/download/v1.1.0/golaunch-cli_1.1.0_darwin_arm64.tar.gz"
      sha256 "0c6fe1e146550d8eced92631c987c8bd31cf1d353ec87390a0049f6fc1a231e3"

      def install
        bin.install "golaunch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/raufzer/golaunch-cli/releases/download/v1.1.0/golaunch-cli_1.1.0_linux_amd64.tar.gz"
        sha256 "7c253a6596e483a37aefce1c60a20926d75feb1ade096e10b795f7d8e01913e0"

        def install
          bin.install "golaunch"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/raufzer/golaunch-cli/releases/download/v1.1.0/golaunch-cli_1.1.0_linux_arm64.tar.gz"
        sha256 "f428d8279a6d7379a43c81ba1efb9b40b0bfba816dc1a8c7ccf42831aa952c8f"

        def install
          bin.install "golaunch"
        end
      end
    end
  end
end
