# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Golaunch < Formula
  desc "Launch your favorite apps with a single command"
  homepage "https://github.com/raufzer/golaunch-cli"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/raufzer/golaunch-cli/releases/download/v1.0.0/golaunch-cli_1.0.0_darwin_amd64.tar.gz"
      sha256 "a583edf6449d35964d9d739ae71a8a36fdce65a93ef089f7b216e363427c58d4"

      def install
        bin.install "golaunch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/raufzer/golaunch-cli/releases/download/v1.0.0/golaunch-cli_1.0.0_darwin_arm64.tar.gz"
      sha256 "e477a9833200e3a462d5e9c92ebcd672a2e965001cb5f34d097b08e1e8bccc38"

      def install
        bin.install "golaunch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/raufzer/golaunch-cli/releases/download/v1.0.0/golaunch-cli_1.0.0_linux_amd64.tar.gz"
        sha256 "8244dbd7a530b729419ea9aa59e6ffde8e652b07e9bdee5418f7dda5f39d3988"

        def install
          bin.install "golaunch"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/raufzer/golaunch-cli/releases/download/v1.0.0/golaunch-cli_1.0.0_linux_arm64.tar.gz"
        sha256 "37cf323d0162ede072f645a1c6f1f0efe08bfe1602a3b4e574ea77522d1ed577"

        def install
          bin.install "golaunch"
        end
      end
    end
  end
end
