# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Golaunch < Formula
  desc "Launch your favorite apps with a single command"
  homepage "https://github.com/raufzer/golaunch-cli"
  version "1.0.0-SNAPSHOT-2a01fb4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/raufzer/golaunch-cli/releases/download/v1.0.0/golaunch-cli_1.0.0-SNAPSHOT-2a01fb4_darwin_amd64.tar.gz"
      sha256 "d8d7527368e46d63416696555e0dc250e5de74f755f864e2e6a8b2e9f0cc9ad8"

      def install
        bin.install "golaunch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/raufzer/golaunch-cli/releases/download/v1.0.0/golaunch-cli_1.0.0-SNAPSHOT-2a01fb4_darwin_arm64.tar.gz"
      sha256 "a5654bae0886024fb89ec9f67bffd60698d30bd06120749c7a73f19f4fef8884"

      def install
        bin.install "golaunch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/raufzer/golaunch-cli/releases/download/v1.0.0/golaunch-cli_1.0.0-SNAPSHOT-2a01fb4_linux_amd64.tar.gz"
        sha256 "69a0c9f49e203ab49e9c35bdf73ffb58739a7dec5ccba030a42dd260fc5073fe"

        def install
          bin.install "golaunch"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/raufzer/golaunch-cli/releases/download/v1.0.0/golaunch-cli_1.0.0-SNAPSHOT-2a01fb4_linux_arm64.tar.gz"
        sha256 "0968ac926a6b2baa6368a0b5bbd29b51c4f86ff7988d947914ca9645b1832506"

        def install
          bin.install "golaunch"
        end
      end
    end
  end
end
