# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Golaunch < Formula
  desc "Launch your favorite apps with a single command"
  homepage "https://github.com/raufzer/golaunch-cli"
  version "2.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/raufzer/golaunch-cli/releases/download/v2.1.0/golaunch-cli_2.1.0_darwin_amd64.tar.gz"
      sha256 "0a1b7f53a1999226785a73d54c40d57daa33f7a0078af83acdf25a40bb11a83d"

      def install
        bin.install "golaunch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/raufzer/golaunch-cli/releases/download/v2.1.0/golaunch-cli_2.1.0_darwin_arm64.tar.gz"
      sha256 "08c19f63c0a450424fed372d790fe39d3a1701290a975c97ff64e8c5190bc50a"

      def install
        bin.install "golaunch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/raufzer/golaunch-cli/releases/download/v2.1.0/golaunch-cli_2.1.0_linux_amd64.tar.gz"
        sha256 "ec5ede0ac7a0932790e7585a443fdc4cb240c209839f69637c7aa0ebacf7d387"

        def install
          bin.install "golaunch"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/raufzer/golaunch-cli/releases/download/v2.1.0/golaunch-cli_2.1.0_linux_arm64.tar.gz"
        sha256 "66e2feb160e9d03f4608edfc1b1c0de779918c9ecca8c0f9586df1a482253490"

        def install
          bin.install "golaunch"
        end
      end
    end
  end
end
